networks:
  softuni-react-net:
    driver: "bridge"
    ipam:
      driver: default
services:
  ###
  # softuni-frontend:
  #   container_name: softuni-cars-app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   networks:
  #     - "softuni-react-net"
  #   ports:
  #     - "5173:80"
  ###
  postgres:
    image: postgres:17.2
    container_name: softuni_postgres
    networks:
      - "softuni-react-net"
    # hide in prod
    ports:
      - "5439:5432"
    restart: always
    volumes: # mounted in this directory, see below
      - ./graphql/volumes/postgres/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  ###
  graphql-engine:
    container_name: softuni_hasura
    image: hasura/graphql-engine:v2.45.3
    ports:
      - "8080:8080"
    networks:
      - "softuni-react-net"
    depends_on:
      - "postgres"
    restart: always
    environment:
      # HASURA_GRAPHQL_MiGRATTIONS_DIR: /metadata
      # HASURA_GRAPHQL_METADATA_DIR: /migrations
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS: "false"
      TZ: Europe/Sofia
volumes:
  db_data:

# docker compose down
# docker compose up --build -d  